import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "Web tutorial",
  description: "Generated by somyi",
};

export default async function RootLayout({ children }) {
  const resq = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
    // cache: "no-store",
    next: { revalidate: 0 },
  });
  const topic = await resq.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topic.map((item) => {
            return (
              <li key={item.id}>
                <Link href={`/read/${item.id}`}>{item.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
